### ISSUE TITLE
This is not compatible with Opencart 2.0.3.1

### ISSUE THREAD

**Issue by taleeshaparker** [craigchristenson/opencart-2checkout-api#3]
There is an fatal error on line 151 $this->response->setOutput($this->render());

**Comment by matthiaz** [comment]
Yeah... noticed the same on 2.2
try changing that to 
```
    $this->response->setOutput($this->load->view($this->template, $data));
```

But I'm getting a TON of php notices, so I can't use this as it is

**Comment by craigchristenson** [comment]
The master branch has been updated to be compatible with OpenCart 2.2.
