### ISSUE TITLE
Indirect modification of overloaded property

### ISSUE THREAD

**Issue by zakeej7** [craigchristenson/opencart-2checkout-api#4]
Hi I uploaded the new files since I wanted to use the api instead of the hosted checkout that comes with standard 2checkout on opencart 2.1.0.2. I get a lot of notices and a fatal error when I try to edit the setting in the payments in the admin. I have pasted them below.

Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 20Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 22Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 23Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 24Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 25Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 26Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 28Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 29Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 30Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 31Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 32Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 33Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 34Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 35Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 36Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 38Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 39Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 44Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 50Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 56Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 59Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 61Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 67Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 73Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 79Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 81Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 86Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 92Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 98Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 104Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 110Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 116Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 121Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 126Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 131Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 136Notice: Indirect modification of overloaded property ControllerPaymentTwoCheckout::$data has no effect in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 142
Fatal error: Call to undefined method ControllerPaymentTwoCheckout::render() in /home/unitycrown/public_html/admin/controller/payment/twocheckout.php on line 151

**Comment by craigchristenson** [comment]
Thank you for reporting. The master branch has been updated to be compatible with OpenCart 2.2.
