### ISSUE TITLE
Could not load template

### ISSUE THREAD

**Issue by zakeej7** [craigchristenson/opencart-2checkout-api#6]
Hi I uploaded the updated files via ftp and when I go and try to edit it it says:

Notice: Error: Could not load template /home/unitycrown/public_html/admin/view/template/payment/twocheckout_api! in /home/unitycrown/public_html/vqmod/vqcache/vq2-system_engine_loader.php on line 86

The files are in the right place so don't know whats wrong?

Please help

**Comment by craigchristenson** [comment]
That path looks correct. Does the directly path "admin/view/template/payment/" contain your other payment method templates on your server?

**Comment by zakeej7** [comment]
Yes that's the path with all the templates.

**Comment by calebh05** [comment]
@zakeej7 Did you remove the 'install' folder after installation completed? This is the cause of the errors that you're seeing.
