### ISSUE TITLE
Notice: Error: Could not load template 

### ISSUE THREAD

**Issue by jooorystore** [craigchristenson/opencart-2checkout-api#7]
Notice: Error: Could not load template /home/xxxx/public_html/jo/admin/view/template/payment/twocheckout_api! in /home/xxxx/public_html/jo/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php on line 86

Version 2.1.0.1

**Comment by calebh05** [comment]
I replied to your other reported issue as well, please remove the 'install' folder from your OC dir and you should then be able to log in to the OC admin panel just fine.
