### ISSUE TITLE
Problem with Opencart 2.3.02

### ISSUE THREAD

**Issue by fikko2** [craigchristenson/opencart-2checkout-api#9]
Hi,

I have opencart version 2.3.0.2, and the shipment extension can not be installed. 
Could you please prepare for version 2.3.0.2

Thank you in advance.

Fikko

**Comment by sunrise-xx** [comment]
This is bug , need fix , it miss .tpl

admin/controller/payment/twocheckout_api.php

Line # 		$this->response->setOutput($this->load->view('payment/twocheckout_api', $data));

change to 
		$this->response->setOutput($this->load->view('payment/twocheckout_api.tpl', $data));

**Comment by craigchristenson** [comment]
We recently updated the module for 2.3 and this issue should be fixed. Please let us know if you are still seeing an error in [the 2.3 branch](https://github.com/craigchristenson/opencart-2checkout-api/tree/v2.3

**Comment by fikko2** [comment]
Thanks. However, I have fixed it. 
Thanks for your help.
